name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pydocstyle

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=120 --show-source --statistics
          pydocstyle . --add-ignore=D202
